#!/bin/bash

# 5 runs
for i in `seq 1 3`; do
    # for each data set
    for d in 0.1 0.5 1 5 10 50 100 500 1000; do
        # on each simulation
        ./run-simulator clopidogrel true Bow RankSvm $d
    done
done    
        